USE [LAKE_CLEAN]
GO

/****** Object:  Table [dbo].[CARGA_FATO]    Script Date: 30/03/2022 17:42:36 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[CARGA_FATO](
	[IDCARGA] [int] NULL,
	[IDATRACACAO] [int] NULL,
	[ORIGEM] [varchar](50) NULL,
	[DESTINO] [varchar](50) NULL,
	[CDMERCADORIA] [varchar](50) NULL,
	[TIPO_OPERACAO_DA_CARGA] [varchar](255) NULL,
	[CARGA_GERAL_ACONDICIONAMENTO] [varchar](255) NULL,
	[CONTEINERESTADO] [varchar](255) NULL,
	[TIPO_NAVEGACAO] [varchar](50) NULL,
	[FLAGAUTORIZACAO] [char](1) NULL,
	[FLAGCABOTAGEM] [char](1) NULL,
	[FLAGCABOTAGEMMOVIMENTACAO] [char](1) NULL,
	[FLAGCONTEINERTAMANHO] [char](1) NULL,
	[FLAGLONGOCURSO] [char](1) NULL,
	[FLAGMCOPERACAOCARGA] [char](1) NULL,
	[FLAGOFFSHORE] [char](1) NULL,
	[FLAGTRANSPORTEVIAINTERIOIR] [char](1) NULL,
	[PERCURSO_TRANSPORTE_EM_VIAS_INTERIORES] [varchar](100) NULL,
	[PERCURSO_TRANSPORTE_INTERIORES] [varchar](100) NULL,
	[STNATUREZACARGA] [varchar](50) NULL,
	[STSH2] [varchar](50) NULL,
	[STSH4] [varchar](50) NULL,
	[NATUREZA_DA_CARGA] [varchar](100) NULL,
	[SENTIDO] [varchar](100) NULL,
	[TEU] [int] NULL,
	[QTCARGA] [int] NULL,
	[VLPESOCARGABRUTA] [float] NULL
) ON [PRIMARY]
GO


