WITH CONSULTA AS(
SELECT 
 [LOCALIDADE] = CF.UF 
,[NUM_ATRACACOES]   = COUNT(*)
,[TEMPO_ATRACADO]   = AVG(DATEDIFF(HOUR,DATA_ATRACACAO,DATA_DESATRACACAO))
,[TEMPO_ESPERA]     = AVG(DATEDIFF(HOUR,DATA_CHEGADA,DATA_ATRACACAO))
,[MES]              = UPPER(CF.MES)
,[NUM_MES]          = DATEPART(MONTH, DATA_DESATRACACAO)
,[ANO]              =  CF.ANO
FROM ATRACACAO_FATO  CF
WHERE CF.SGUF = 'CE'
GROUP BY CF.UF, CF.MES, CF.ANO ,DATEPART(MONTH, DATA_DESATRACACAO)

UNION

SELECT 
 [LOCALIDADE] = CF.REGIAO_GEOGRAFICA 
,[NUM_ATRACACOES]   = COUNT(*)
,[TEMPO_ATRACADO]   = AVG(DATEDIFF(HOUR,DATA_ATRACACAO,DATA_DESATRACACAO))
,[TEMPO_ESPERA]     = AVG(DATEDIFF(HOUR,DATA_CHEGADA,DATA_ATRACACAO))
,[MES]              = UPPER(CF.MES)
,[NUM_MES]          = DATEPART(MONTH, DATA_DESATRACACAO)
,[ANO]              =  CF.ANO
FROM ATRACACAO_FATO  CF
WHERE  REGIAO_GEOGRAFICA = 'NORDESTE'
GROUP BY CF.REGIAO_GEOGRAFICA, CF.MES, CF.ANO,DATEPART(MONTH, DATA_DESATRACACAO)

UNION

SELECT 
 [LOCALIDADE]       = 'Brasil'
,[NUM_ATRACACOES]   = COUNT(*)
,[TEMPO_ATRACADO]   = AVG(DATEDIFF(HOUR,DATA_ATRACACAO,DATA_DESATRACACAO))
,[TEMPO_ESPERA]     = AVG(DATEDIFF(HOUR,DATA_CHEGADA,DATA_ATRACACAO))
,[MES]              = UPPER(CF.MES)
,[NUM_MES]          = DATEPART(MONTH, DATA_DESATRACACAO)
,[ANO]              =  CF.ANO
FROM ATRACACAO_FATO  CF
GROUP BY CF.MES, CF.ANO,DATEPART(MONTH, DATA_DESATRACACAO)

) 
SELECT  
 A.LOCALIDADE 
,[NÚMERO DE ATRACAÇÕES]      = A.[NUM_ATRACACOES]
,[VARIACAÇÃO PERC%]          = ISNULL(CAST((A.NUM_ATRACACOES/B.NUM_ATRACACOES-1)*100.0 AS NUMERIC(5,2)),0)
,[TEMPO ATRACADO MÉDIO (H)]  = [TEMPO_ATRACADO]
,[TEMPO DE ESPERA MÉDIO (H)] = [TEMPO_ESPERA]
,[MÊS]                       = A.[MES]
,[ANO]                       = A.[ANO]

FROM CONSULTA A
LEFT JOIN (SELECT CAST([NUM_ATRACACOES] AS FLOAT)[NUM_ATRACACOES] ,LOCALIDADE, [NUM_MES], [ANO]
           FROM CONSULTA
		   ) B ON  A.LOCALIDADE = B.LOCALIDADE   
		       AND A.[NUM_MES]  = B.[NUM_MES] 
			   AND A.[ANO]-1    = B.[ANO]
WHERE a.ANO IN ('2020','2021') 
ORDER BY A.LOCALIDADE,A.[ANO], A.[NUM_MES]

